---

- name: Check if kubectl is installed
  command: kubectl version --client --short
  register: kubectl_check
  changed_when: false
  failed_when: false


- name: Install kubectl
  shell: |
    if ! command -v kubectl &> /dev/null; then    
      curl -LO "https://dl.k8s.io/release/v{{ version }}/bin/linux/amd64/kubectl"
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin/
    fi
  when: kubectl_check.rc != 0