---

- name: Check if Kind is installed
  command: kind version
  register: kind_check
  changed_when: false
  failed_when: false

- name: Install Kind
  shell: |
    if ! command -v kind &> /dev/null; then
      curl -Lo ./kind https://kind.sigs.k8s.io/dl/v{{ version }}/kind-linux-amd64
      chmod +x ./kind
      sudo mv ./kind /usr/local/bin/kind
    fi
  when: kind_check.stdout_lines | length == 0